[[libcudf]]
arch = "x86_64"
cuda = "12.0"
cxxstring_abi = "cxx11"
git-tree-sha1 = "860d1c828af5c35f997c51da637d6d28295932b8"
lazy = true
libc = "glibc"
os = "linux"

    [[libcudf.download]]
    sha256 = "0b5bfd6106e61daf2c47b3b9cd5d960595f630d828af675180444bcbbbbaaa89"
    url = "https://github.com/tylerjthomas9/libcudf_jll/releases/download/libcudf-v23.8.0+0/libcudf.v23.8.0.x86_64-linux-gnu-cxx11-cuda+12.0.tar.gz"
